# Generated by Django 5.2.5 on 2025-08-28 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0002_perfil_pais_perfil_telefono'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
