# Generated by Django 5.2.7 on 2026-01-20 17:39

import django.db.models.deletion
import snake_shop.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0012_pedido_descuento_pedido_envio_pedido_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='FolioSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pedido', 'Pedido'), ('ticket', 'Ticket de Soporte')], max_length=20, unique=True)),
                ('anio', models.PositiveIntegerField()),
                ('correlativo', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='folio',
            field=models.CharField(default='SS-temp-00000', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='flow_order',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='flow_token',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='raw_webhook',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='soporte/archivos/%Y/%m/%d/', validators=[snake_shop.models.validar_archivo_soporte]),
        ),
        migrations.AlterField(
            model_name='transaccion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('rechazado', 'Rechazado'), ('error', 'Error')], default='pendiente', max_length=50),
        ),
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='soporte/archivos/%Y/%m/%d/', validators=[snake_shop.models.validar_archivo_soporte])),
                ('tipo_mime', models.CharField(blank=True, max_length=100)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='snake_shop.ticketsoporte')),
            ],
        ),
    ]
