# Generated by Django 5.2.7 on 2026-01-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0013_foliosequence_pedido_folio_transaccion_flow_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='folio',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
