# Generated by Django 6.0.1 on 2026-01-22 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0014_alter_pedido_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='en_promocion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio_promocion',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
