# Generated by Django 6.0.1 on 2026-01-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0016_alter_pedido_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='costo_envio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_despacho',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_despacho', 'En Despacho'), ('completado', 'Completado'), ('retiro', 'Retiro en tienda')], default='pendiente', max_length=20),
        ),
    ]
