# Generated by Django 6.0.1 on 2026-01-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0017_pedido_costo_envio_alter_pedido_estado_despacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
