# Generated by Django 6.0.1 on 2026-01-26 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0018_alter_pedido_ciudad_alter_pedido_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='envio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado_despacho',
            field=models.CharField(choices=[('en_despacho', 'Despacho a domicilio'), ('retiro', 'Retiro en tienda')], default='en_despacho', max_length=20),
        ),
    ]
