# Generated by Django 6.0.1 on 2026-01-26 15:43

import django.db.models.deletion
import snake_shop.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0019_alter_pedido_envio_alter_pedido_estado_despacho'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketComentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('es_staff', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='snake_shop.ticketsoporte')),
            ],
        ),
        migrations.CreateModel(
            name='TicketComentarioAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='soporte/comentarios/%Y/%m/%d/', validators=[snake_shop.models.validar_archivo_soporte])),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='snake_shop.ticketcomentario')),
            ],
        ),
    ]
