# Generated by Django 5.2.5 on 2025-08-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0004_producto_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='estado_despacho',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_despacho', 'En Despacho'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
