# Generated by Django 5.2.5 on 2025-08-29 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0005_pedido_estado_despacho'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='comuna',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='direccion',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
