# Generated by Django 5.2.5 on 2025-08-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0006_perfil_comuna_alter_perfil_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='productos/%Y/%m/%d/'),
        ),
    ]
