# Generated by Django 5.2.5 on 2025-08-30 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0007_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, upload_to='imagenes/%Y/%m/%d/'),
        ),
    ]
