# Generated by Django 5.2.7 on 2025-11-07 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snake_shop', '0009_remove_perfil_is_seller_alter_perfil_rol_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('tipo_solicitud', models.CharField(choices=[('falla', 'Falla/Reparación'), ('garantia', 'Uso de Garantía'), ('consulta', 'Consulta Técnica'), ('devolucion', 'Solicitud de Devolución')], max_length=20)),
                ('numero_pedido', models.CharField(blank=True, help_text='Obligatorio para temas de garantía o devoluciones.', max_length=50, null=True)),
                ('asunto', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='soporte/archivos/%Y/%m/%d/')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En Proceso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='abierto', max_length=20)),
                ('folio', models.CharField(editable=False, max_length=50, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-creado'],
            },
        ),
    ]
